services:
  db:
    image: postgres:17
    container_name: db_app
    env_file:
      - .env-non-dev
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: qwerty

  redis:
    image: redis:7
    container_name: redis_app

  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: fastapi_app
    command: ["/fastapi_app/docker/app.sh"]
    ports:
      - "9999:8000"
    depends_on:
      - db
      - redis
